### ISSUE TITLE
Some confusing parts of the examples 

### ISSUE THREAD

**Issue by brmscheiner** [mattiasw/ExifReader#119]
First off thanks for building this library, it's very helpful! 

I got it working but I was very confused by a few lines of code in the [example](https://mattiasw.github.io/ExifReader/esm/):

```
document.querySelector('html').setAttribute('data-initialized', '');
window.exifReaderClear();
window.exifReaderListTags(tags);
window.exifReaderError(error.toString());
```

When I import ExifReader I don't get any of these methods attached to the window and I don't understand what purpose it serves to set that attribute. After thinking about it for a while I have come to assume that they are used by the html/js that powers the demo page, but that wasn't immediately obvious. 

I would suggest either showing the full code for the demo page, removing these lines, or ignoring me :)

**Comment by mattiasw** [comment]
I may have gotten a bit too carried away when refactoring. :-) You are correct, they are helper functions for the demo pages and I didn't want to include those for every example and it was not really interesting for knowing how to use the library. In the new PR I have removed it from the code that is shown to hopefully make it clearer. I will merge it later in case you want to have a look. Big thanks for pointing this out since it stops people from quickly starting to use the library.

**Comment by brmscheiner** [comment]
PR looks great, thanks for the quick response :)
