### ISSUE TITLE
Low vulnerability with xmldom dependency

### ISSUE THREAD

**Issue by fgoulet** [mattiasw/ExifReader#145]
### Description
Would it be possible to update the xmldom dependency to 0.5.0 ?

Thanks !  

npm audit

Low             Misinterpretation of malicious XML input                      
Package         xmldom                                                        
Patched in      >=0.5.0                                                       
Dependency of   exifreader                                                    
Path            exifreader > xmldom

**Comment by mattiasw** [comment]
I looked at it before but since that "minor" update of xmldom has several breaking changes and the severity is low I decided to wait with it. But I can have closer look later this week and see how much the changes affect ExifReader.

**Comment by mattiasw** [comment]
I can't upgrade xmldom without making a major version bump since it only supports Node 10+ now and I'm hesitant to do that. On the other hand, as I understand the vulnerability it only appears when parsing AND serializing. ExifReader only uses it for parsing. I will leave this for ExifReader version 4 together with other breaking changes.

**Comment by mattiasw** [comment]
The xmldom package is upgraded in version 4.0.0.
