### ISSUE TITLE
Reading toString() of undefined

### ISSUE THREAD

**Issue by kachurovskiy** [mattiasw/ExifReader#170]
### Description

Exception on a particular file:

<img width="414" alt="exif-reader-toString-of-undefined" src="https://user-images.githubusercontent.com/517919/147725616-319db075-9bd2-48e2-bfea-2ece07915f03.png">

**How to reproduce**

1.  Read exif on this file: ![17](https://user-images.githubusercontent.com/517919/147725590-bfe83cd4-4d42-43cf-b1a9-40180dd5ae38.jpg)

**Comment by mattiasw** [comment]
Hi! Thanks for reporting. I need more details on your setup to be able to investigate since I don't get this myself. At least web browser or Node version and ExifReader version. Best would be if you could describe how it can be reproduced using one of the implementations on the examples site: https://mattiasw.github.io/ExifReader/

**Comment by kachurovskiy** [comment]
Looks like I'm simply passing in `undefined` which fails in here:

```
if (buffer.toString('ascii', 0, 5) !== 'Exif\0')
```

Maybe checking `if (!buffer)` before that would give a clearer error message for future users (or return empty object). Thank you for looking into this.

**Comment by mattiasw** [comment]
To which function do you pass in `undefined`? I can't find the code you're referencing, probably because of transpilation. I get a clear error message when I pass in `undefined` to the `load()` function: `Passed buffer type is unsupported.`. There is also an undocumented function called `loadView()` that gives a not so clear message though and I will update that, so thanks for helping me find it. It doesn't sound like the same error as you're experiencing though: `Cannot read property 'byteLength' of undefined`
