### ISSUE TITLE
Some number values are being provided as fraction strings

### ISSUE THREAD

**Issue by lucypoulton** [mattiasw/ExifReader#204]
### Description

Some number values are being provided as fraction strings.

For example, [this image](https://www.icloud.com/iclouddrive/06b5WEQjTNJ-5ym5AvsS_1vyA#IMG_1316) (it's too big to attach) was shot at ƒ/7.1, so I would expect `FNumber` to be the number `7.1`, which aligns with the type declarations. Instead I get the string `"71/10"`. The same thing happens with the focal length of 250mm, expected `FocalLength` to be `250`, instead `"250/1"`. 

**Additional details**
ExifReader version 4.5.1. Reproducible across all formats on the demo site.

**Comment by mattiasw** [comment]
Hi! I will have a look later in the week.

**Comment by mattiasw** [comment]
So, these appear to be XMP tags and XMP tags are always strings which generally have not been parsed and formatted differently depending on the content. They are just showed the same way the original program or device wrote them into the image file. This is not a problem, I'm just mentioning the history of it, and there are actually a couple of parsed values since before (specifically GPS and orientation). I took the time to also convert the ones I could find in your example image. Thanks for the suggestion! It's released as version 4.6.0.
