### ISSUE TITLE
Exif tags missing from extracted tags

### ISSUE THREAD

**Issue by snowboundvt** [mattiasw/ExifReader#212]
### Description

If I view the metadata of the attached photo in Photoshop, Mac Preview app or export the tags using ExifTool, Exif tags are present. Using ExifReader, it only returns the 'itpc' and 'jfif' tag groups.

**Additional details**

- ExifReader version: 4.8
- Web browser and version: Mac Chrome 107
- Can you reproduce the bug on the examples site?

Yes. Upload the attached test photo to the "global object" example and compare it to the ExifTool output.

![95085_D0050](https://user-images.githubusercontent.com/117747364/200589359-bba48677-98df-4610-9213-00d333d79ba1.jpg)

Exiftool output: 
[ExifTool-output.txt](https://github.com/mattiasw/ExifReader/files/9962029/ExifTool-output.txt)

**What I expected would happen:**

The Exif tags returned from ExifReader are similar to what ExifTool exports.

**What really happened:**

ExifReader only returns 'itpc' and 'jfif' tag groups.

**Comment by mattiasw** [comment]
That's interesting... I'll look into it.

**Comment by mattiasw** [comment]
Fixed and released as version 4.8.1.

It had to do with something called fill bytes that sometimes can be inserted at certain locations. Strangely enough I had not encountered these before during these twelve years. None of my other test images have a fill byte in them. Big thanks for reporting this so that it could finally be fixed.

**Comment by snowboundvt** [comment]
Incredible turn-around for this fix! Thank you very much.
