### ISSUE TITLE
Exifr fails to read PNG image parameters if the field is 1000+ characters

### ISSUE THREAD

**Issue by manuelurenah** [mattiasw/ExifReader#241]
### Description

We just ran into an issue where it seems that the package struggles to read parameters from PNGs if the field is 1000 or more characters. You can actually see this behavior in the [playground](https://mattiasw.github.io/ExifReader/global/) itself by using these test images:

[999 character PNG](https://scottymac.s3.amazonaws.com/stable-diffusion/testing/Test-working-999-characters.png) (returns parameters)
[1000 character PNG](https://scottymac.s3.amazonaws.com/stable-diffusion/testing/Test-failing-1000-characters.png) (doesn't return parameters)
Is this a known issue? I browsed the codebase and didn't see anything tied to that character limit.

**Additional details**

- ExifReader version: 4.12.1
- Web browser and version: Google Chrome - Version 114.0.5735.133 (Official Build) (x86_64)
- Node version: v16
- Can you reproduce the bug on the examples site? If so, using which implementation (global object, AMD, and/or ES module)? 
  - The bug can be reproduced in all example pages from the site

**How to reproduce**

[999 character PNG](https://scottymac.s3.amazonaws.com/stable-diffusion/testing/Test-working-999-characters.png) (returns parameters)
[1000 character PNG](https://scottymac.s3.amazonaws.com/stable-diffusion/testing/Test-failing-1000-characters.png) (doesn't return parameters)

1.  Go to example site
2.  Upload example images provided above
3.  png file with 999 characters in the params works, but png file with 1000 characters doesn't load `parameters` from exif data

**What I expected would happen:**

Provide parameters data from exif with more than 1000 characters

**What really happened:**

No parameters when png file has more than 999 characters in the parameters

**Comment by mattiasw** [comment]
Hi! Unfortunately it's because the 1000 character image is using compressed tags which is not supported. There is already another ticket for that: #236. I have started on it but it's a lot of work because it needs some rewriting and changes to the library API so it's paused for the moment. I'm hopeful it's possible to do for both Node.js and recent web browsers but I'm currently not sure so we'll have to see. I may get some time to look closer at it during the coming months. In the meantime, if it's possible for you to store the tags as uncompressed it should work.

**Comment by mattiasw** [comment]
I finally got this working. Released as 4.20.0. Make sure to pass in `async: true` in the options parameter if you're not already using the async version.

**Comment by jgautier2** [comment]
coucou,

je l’ai fait hier soir.

bisous

P
