### ISSUE TITLE
DateTime wrong format

### ISSUE THREAD

**Issue by Tindtily** [mattiasw/ExifReader#371]
### Description

        "DateTime": {
            "id": 306,
            "value": [
                "2024:08:07 10:03:13"
            ],
            "description": "2024:08:07 10:03:13"
        },

**How to reproduce**

any jpeg file to load

**What I expected would happen:**

2024-08-07 10:03:13

**What really happened:**

2024:08:07 10:03:13

Was the date format intentionally set up this way?

In addition, is it possible to provide the date format with milliseconds value?

**Comment by mattiasw** [comment]
Hi!

This is the format used in the Exif specification and it's the actual string stored in the image file. I can see why you don't want this but I don't think the library should make the conversion since it's the standard way (for Exif) of writing a date (even though I agree they did it wrong).

Regarding the milliseconds there are these tags you can look at, if your images have them: `SubsecTime`, `SubsecTimeOriginal`, `SubsecTimeDigitized`. They will be a string. If it's `130` it means `0.130` and if it's `1301` it means `0.1301`.

**Comment by Tindtily** [comment]
thx
