### ISSUE TITLE
is it possible to modify the meta data?

### ISSUE THREAD

**Issue by Divine1** [mattiasw/ExifReader#52]

**Comment by mattiasw** [comment]
That functionality has crossed my mind, but at the moment it's not possible. It would probably be a larger project to add that.

**Comment by Divine1** [comment]
do you have made plans for adding it?

**Comment by mattiasw** [comment]
No, not really. But you got me interested. :-) I won't make any promises since I have quite limited time right now, but I'm at least going to have a look at what it will take. If you would use such a feature, would it have to be possible to write to all of the different types of meta data (Exif, IPTC and XMP) or just one or two of them?

**Comment by Divine1** [comment]
Thank you mattias. 

IPTC, EXIF, XMP. Implementing one by one in this order would be fine. I was just thinking about metadata in images. I actually have no urgent need for the feature. I was just looking around

**Comment by mattiasw** [comment]
This is going to be tricky. I think I will postpone this for a while. A lot of stuff would have to be changed and added. If a lot of people requests it I may reconsider.

**Comment by Divine1** [comment]
i'll get back to you when i have enough time to contribute to this.

**Comment by mattiasw** [comment]
Closing this for now. May reopen if interest increases, but generally I think it would probably make sense with a separate library for this. The code would be very different from this one and would also add a lot of extra bytes which most of the users would not be happy about.

**Comment by LeahPike** [comment]
I'm looking for something to strip the orientation once I've read it as I'm having great issues with browsers and my canvas where some will rotate the image themselves based off the EXIF and some do not!

**Comment by mattiasw** [comment]
As I understand it there's a somewhat new feature where web browsers recently started auto-rotating images using the meta data. I think that's why you're seeing a difference between clients. You could try and set `image-orientation: none;` on the image. I'm not sure it's going to work but the default value of this property is what some browsers changed to `from-image`. And since you're mentioning canvas this may not be applicable at all for you.

There are more details in this issue: #99 

Regarding the write functionality, I don't think that will happen any time soon for ExifReader, if ever. That should probably be its own library to not make this one unnecessarily large for most people.

**Comment by LeahPike** [comment]
Yeah I think that is the issue. Thank you for your reply.

I have a set of test images with different orientations which I used to test my canvas when I originally made it, and now it's doing a different behaviour with the same images. I am trying to use the image-orientation tag but it's still doing some strange things, with the image width and height 😕
