### ISSUE TITLE
Convert people from exif-js

### ISSUE THREAD

**Issue by fatso83** [mattiasw/ExifReader#57]
### Description

Hi, Mattias. This library seems like what exif-js could have been and it also seems to have a much better API than its cousin (exif-js/exif-js#142) and using more modern internals, not to mention better build tools. And tests! You have tests, whee!

As its ugly cousin is essentially dead (ref exif-js/exif-js#206) I know a lot of people are looking for an alternative. Your library seems like the right thing to go for, but I guess people wonder "why does this seemingly better alternative have 2% of the popularity of its ugly cousin"? I think branding and marketing is basically the answer to that :-) 

I would have a little section of the README dedicated to people coming from Exif JS for an alternative, listing the pros (and cons?) of using ExifReader. Then I'd refer people here using the exif-js issue tracker and pull requests.

**Comment by mattiasw** [comment]
Hi! I've also been wondering that. :-D But yeah, can't say I've tried to reach out that much.

I would be happy to update the README with such a section. Do you have any pros and cons in mind? I don't really know much about exif-js, especially not what it's doing well and not so well (since it didn't (publically) exist when I was exploring exif libraries and ended up writing my own).

**Comment by fatso83** [comment]
Better API, doesn't break if some consumer uses strict mode, more frequently updated amd released. Yeah, and that it actually has a maintainer :-)

**Comment by mattiasw** [comment]
Added in #61.
