### ISSUE TITLE
Warning during install on Angular

### ISSUE THREAD

**Issue by jbdioli** [mattiasw/ExifReader#71]
There is some waning when we install it under angular. If you are interested in. :)

![image](https://user-images.githubusercontent.com/48244032/69485665-f63c5180-0e42-11ea-8376-2c9298bee24c.png)

**Comment by mattiasw** [comment]
`fsevents` is only used on MacOS, it should not be a problem (it's a common warning on non-MacOS systems). But it doesn't look like that warning is because of ExifReader. It mentions other packages like `wepack-dev-server` which ExifReader doesn't include. My guess is it's other parts of your project that cause the warnings.
